name = "Baromc"
author = "EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cdb615ffd12cddc84f6f6cfa8a23c05e1d432e0e37a62e47dd477ec48296903"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
